name: APK-J Build

on:
#  push:
#    branches:
#      - main
#  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Clone Project
        run: git clone -b main --depth=1 https://github.com/cai512/TVBoxOSC-J
      - name: DIY
        run: |
          chmod +x diy-J.sh
          bash ${{ github.workspace }}/diy-J.sh
      - name: Build With Gradle
        run: |
          num=$(find ${{ github.workspace }} -name gradlew  | awk -F"/" '{print NF-1}')
          DIR=$(find ${{ github.workspace }} -name gradlew  | cut -d \/ -f$num)
          cd $DIR
          chmod +x gradlew
          ./gradlew assemblerelease --build-cache --parallel --daemon --warning-mode all
      - name: Prepare App
        run: |
          mkdir -p ${{ github.workspace }}/apk/
          for file in `find ~ -name "*.apk" -print`; do
            mv "$file" ${{ github.workspace }}/apk/
          done
      - name: Whether Or Not to Publish
        if: ${{ inputs.donotpublish && env.commit }}
        run: |
          echo "commit=" >> $GITHUB_ENV
      - name: Release and Upload Assets
        uses: softprops/action-gh-release@v1
        if: ${{ env.commit }}
        with:
          name: ${{ env.tag }}
          tag_name: ${{ env.tag }}
          body: "Credit: ${{ matrix.userName }}/${{ matrix.repoName }}\n
                 Commit: ${{ env.commit }}"
          files: |
            TVBoxOSC/apk/*
            TVBoxOSC/${{ env.commitS }}-source.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        donotpublish:
        description: '构建后不发布新版'
        required: false
        type: boolean
      - name: Upload App To Artifact
        uses: actions/upload-artifact@v3
        with:
          name: tvbox_Jun.Pyramid
          path: ${{ github.workspace }}/apk/*
